CREATE OR REPLACE PROCEDURE getMasters(curs OUT sys_refcursor)
IS
BEGIN
    OPEN curs FOR
    SELECT
        E.EMAIL,
        E.Surname,
        MASTERS.NUMBEROFCOMPLETEDORDERS,
        SUM(CASE WHEN O.OrderStateId = 2 THEN O.OrderPrice ELSE 0 END) AS NumberOfReturnedOrders,
        TYPEOFAPPLIANCES.NAME AS TYPENAME
    FROM
        Masters
    JOIN
        EMPLOYEES E ON E.ID = MASTERS.EMPLOYEESID
    JOIN
        TYPEOFAPPLIANCES ON MASTERS.SPECTYPEID = TYPEOFAPPLIANCES.ID
    LEFT JOIN
        ORDERS O ON E.ID = O.EMPLOYEEID
    GROUP BY
        E.EMAIL, E.Surname, TYPEOFAPPLIANCES.NAME, MASTERS.NUMBEROFCOMPLETEDORDERS
    ORDER BY
        NumberOfReturnedOrders DESC;
END;
