CREATE OR REPLACE PROCEDURE getModelsWithTypeAndProducer(in_model IN MODELS.MODEL%TYPE,
    servpacks OUT SYS_REFCURSOR
)
IS
BEGIN
    IF in_model IS NULL OR TRIM(in_model) = '' THEN
        OPEN servpacks FOR
            SELECT MODELS.MODEL, TYPEOFAPPLIANCES.NAME, PRODUCERS.PRODUCER
            FROM MODELS
            JOIN TYPEOFAPPLIANCES ON MODELS.TYPEID = TYPEOFAPPLIANCES.ID
            JOIN PRODUCERS ON PRODUCERS.ID = MODELS.PRODUCERID;
    ELSE
        OPEN servpacks FOR
            SELECT MODELS.MODEL, TYPEOFAPPLIANCES.NAME, PRODUCERS.PRODUCER
            FROM MODELS
            JOIN TYPEOFAPPLIANCES ON MODELS.TYPEID = TYPEOFAPPLIANCES.ID
            JOIN PRODUCERS ON PRODUCERS.ID = MODELS.PRODUCERID
            WHERE MODELS.MODEL LIKE '%' || in_model || '%';
    END IF;
    DBMS_OUTPUT.ENABLE();
    DBMS_SQL.RETURN_RESULT(servpacks);
END getModelsWithTypeAndProducer;
/
