-- Предоставление привилегий для работы с OLAP объектами
GRANT CREATE SESSION TO GAE_1;
GRANT CREATE CUBE TO GAE_1;
GRANT CREATE DIMENSION TO GAE_1;
GRANT CREATE HIERARCHY TO GAE_1;
GRANT CREATE MATERIALIZED VIEW TO GAE_1;

GRANT ADVISOR TO GAE_1;

-- Привилегии на выполнение OLAP-запросов
GRANT EXECUTE ON DBMS_CUBE TO GAE_1;
GRANT EXECUTE ON DBMS_CUBE_ADVISE TO GAE_1;
GRANT EXECUTE ON DBMS_DIMENSION TO GAE_1;
GRANT EXECUTE ON DBMS_HIERARCHY TO GAE_1;

-- Предоставление роли OLAP_USER пользователю GAE_1
GRANT OLAP_USER TO GAE_1;
GRANT OLAP_DBA TO GAE_1;
